# Generated by Django 2.2.17 on 2021-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='role',
            field=models.IntegerField(choices=[(0, '研究'), (1, '开发'), (2, '测试'), (3, '运营'), (4, '产品')], verbose_name='分组角色'),
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='jira',
            unique_together=set(),
        ),
    ]
